[window]
startup_mode = "Maximized"
# "Windowed" | "Maximized" | "Fullscreen" | "SimpleFullscreen"
padding = { x = 2, y = 2 }
decorations = "None" 
# "Full" | "None" | "Transparent" | "Buttonless"
opacity = 1.0

[font]
# Fuente principal
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }

# Fuente en negrita
bold = { style = "Bold" }

# Fuente en cursiva
italic = { style = "Italic" }

# Fuente en negrita + cursiva
bold_italic = { style = "Bold Italic" }

# Tamaño de fuente
size = 12.0

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "On" }
blink_interval = 500
blink_timeout = 5
unfocused_hollow = true

[bell]
animation = "EaseOutExpo"
duration = 0
