-- require("config.options")
-- require("config.lazy")
-- require("config.lsp")
-- require("config.keymaps")
-- require("config.autocmds")

require("config.options")
require("config.autocmds")
require("config.lazy")
require("config.lsp")
require("config.keymaps")
